---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - basic-auth.secret.enc.yaml
  - helm-release.yaml
  - service-monitor.yaml
  - virtualservice.yaml
  - prometheus-rule.yaml
  - tls-store
  - middlewares
