---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - home-assistant.secrets.enc.yaml
  - home-assistant.configmap.yaml
  - prometheus.secrets.enc.yaml
  - helm-release.yaml
  - virtual-service.yaml
patchesStrategicMerge:
  - ./gotk-patches.yaml
