---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../kube-system
  - ../../flux-system
  - ../../networking
  - ../../observability
  - ../../home-automation
  - ../../security
  - ../../system-upgrade
  - ../../development
