---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - focalboard
  - frigate
  - home-assistant
  - mosquitto
  - ubiquiti-watcher
  - unifi-downloader
  - zigbee2mqtt
  - zwavejs2mqtt
  - esphome
  - rtlamr-collect
